### ISSUE TITLE
Export merged cells

### ISSUE THREAD

**Issue by marekurbanski** [Spreadsheets/jQuery.sheet#3]
Hi,
After merged some cells I tried to export them (I tried to do this in example dts.test.html)
After run this, I merged some cells from console and till this everything look correct.
While exporting data (I can't see in code /colspan="2"/ ) and new sheet is not correct merged.
It has cell with style display=none but the previous one doesnt have the "colspan=2"

Is this some bug ?
Please help :)

rgds
Marek

**Comment by robertleeplummerjr** [comment]
I believe this has been fixed in the sww branch.
