### ISSUE TITLE
Replace content of spreadsheet without removing menu

### ISSUE THREAD

**Issue by ssekhonissc** [Spreadsheets/jQuery.sheet#64]
Hi I'm having an issue loading data from JSON into the spreadsheet. I would like to modify the content of the spreadsheet. Save the content, then reload saved content.

Original screenshot (screenshot #1)
![screenshot1](https://cloud.githubusercontent.com/assets/11321287/6494019/a966b4d8-c273-11e4-8e83-c517eafb4536.png)

1. When I use the following: 

jQuery('#selectedSheet').html(jQuery.sheet.dts.toTables.json(res.data)).sheet();

The data is replaced, however the menu's are removed (screenshot #2)

![screenshot2](https://cloud.githubusercontent.com/assets/11321287/6494018/a9654b52-c273-11e4-94d2-02a9d07b85bf.png)

2. When I use the following: 

var sheet = jQuery('#selectedSheet').getSheet();
sheet.openSheet(jQuery.sheet.dts.toTables.json(res.data));

The data remains unchanged and the menu is moved below the spreadsheet content.
![screenshot3](https://cloud.githubusercontent.com/assets/11321287/6494017/a9618bac-c273-11e4-8a4a-c6b98d71683f.png)

I would like to replace the content of spreadsheet with the JSON data. However, I would like to keep the menu and the original state of the spreadsheet.

Please help,

Sonu

**Comment by robertleeplummerjr** [comment]
I'm addressing this right now.

**Comment by robertleeplummerjr** [comment]
Try this:
```javascript
var menuLeft = $('<a>'),
  menuRight = $('<a>'),
  sheet = $('#sheet').sheet({
    menuLeft: menuLeft,
    menuRight: menuRight
  }),
  jS = sheet.getSheet();

jS.kill();

var newSheet = $('#sheet').sheet({
  menuLeft: menuLeft,
  menuRight: menuRight
});
```
